=== DenysKulikov/block2/src/main/resources/company.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="BuildingEnumType">
        <xs:all>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="baseCost" type="xs:decimal"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="CostEstimateType">
        <xs:all>
            <xs:element name="cost" type="xs:decimal"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="BuildingType">
        <xs:all>
            <xs:element name="buildingType" type="BuildingEnumType"/>
            <xs:element name="buildingDescription" type="xs:string"/>
            <xs:element name="costEstimate" type="CostEstimateType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="BuildingsType">
        <xs:sequence>
            <xs:element name="building" type="BuildingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:all>
            <xs:element name="buildings" type="BuildingsType"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="Employees">
        <xs:sequence>
            <xs:element name="employee" type="EmployeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="companyType">
        <xs:all>
            <xs:element name="employees" type="Employees"/>
            <xs:element name="name" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:element name="company" type="companyType"/>
</xs:schema>

=== DenysKulikov/block2/src/main/resources/company.xml
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="company.xsd" id="1">
    <name>Building</name>
    <employees>
        <employee id="1">
            <firstName>Alice</firstName>
            <lastName>Johnson</lastName>
            <position>BUILDER</position>
            <buildings>
                <building id="1">
                    <buildingType>
                        <type>COMMERCIAL</type>
                        <baseCost>180000.00</baseCost>
                    </buildingType>
                    <buildingDescription>Desc 1</buildingDescription>
                    <costEstimate>
                        <cost>1000000.00</cost>
                    </costEstimate>
                </building>

                <building id="2">
                    <buildingType>
                        <type>COMMERCIAL</type>
                        <baseCost>180000.00</baseCost>
                    </buildingType>
                    <buildingDescription>Desc 2</buildingDescription>
                    <costEstimate>
                        <cost>1000000.00</cost>
                    </costEstimate>
                </building>
            </buildings>
        </employee>

        <employee id="2">
            <firstName>Sam</firstName>
            <lastName>Johnson</lastName>
            <position>BUILDER</position>
            <buildings>
                <building id="3">
                    <buildingType>
                        <type>RESIDENTIAL</type>
                        <baseCost>120000.00</baseCost>
                    </buildingType>
                    <buildingDescription>Desc 1</buildingDescription>
                    <costEstimate>
                        <cost>1000000.00</cost>
                    </costEstimate>
                </building>
            </buildings>
        </employee>
    </employees>
    
    <customers>
        <customer id="1">
            <firstName>John</firstName>
            <lastName>Doe</lastName>
            <payment id="1">
                <amount>100000.00</amount>
                <paymentDate>2023-01-15</paymentDate>
            </payment>
        </customer>
    </customers>
</company>
